koishijs/koishi

package.json
packages/test-utils/src/mocks.ts

test: add experimental shouldMatchSnapshot

---

packages/plugin-mongo/src/database.ts

```ts
export interface Config {
protocol?: string
}
```
```ts
let mongourl = `${this.config.protocol || 'mongodb'}://`
```

[plugin-mongo] Add protocol config

---

packages/koishi-utils/src/string.ts
packages/koishi-utils/tests/string.spec.ts
packages/plugin-status/src/index.ts

feat(status): status template & utils.interpolate()

---

packages/plugin-mysql/src/index.ts
packages/plugin-schedule/src/database.ts

fix(schedule): fix mysql init

---

packages/plugin-github/src/events.ts

fix(github): fix typo

---

.eslintrc.yml
packages/plugin-chat/client/chat.vue
packages/plugin-chat/src/receiver.ts
packages/plugin-webui/client/components/chat-panel.vue
packages/plugin-webui/client/components/message.vue
packages/plugin-webui/client/components/virtual-list/index.vue
packages/plugin-webui/client/components/virtual-list/virtual.ts
packages/plugin-webui/client/index.ts
packages/plugin-webui/client/tsconfig.json
packages/plugin-webui/client/views/layout/overlay.vue

feat(webui): virtual message list

---

packages/adapter-discord/src/bot.ts
packages/adapter-kaiheila/src/bot.ts

`file://` → `file:///`
`protocol://host:port/path/file.ext` → `file:///path/to/image.png`

fix(adapter): Fix local image sending

---

packages/adapter-discord/src/bot.ts
packages/adapter-discord/src/types.ts

- 移除了不必要的 `async` 关键字
- 新增 `$setGroupName` `$setGroupCard` 方法，与其他 adapter 同步

chore(discord): batch improvements

---

packages/plugin-mongo/src/database.ts

fix(mongo): percent encoding in connection string

---

packages/koishi-core/src/parser.ts
packages/koishi-core/tests/parser.spec.ts

fix(core): command option type bug

---

.github/workflows/test.yaml
.mocharc.js
packages/plugin-mongo/tests/database.spec.ts
packages/plugin-mysql/src/database.ts
packages/plugin-mysql/tests/database.spec.ts

fix(orm): sql statement lacks fields when creating tables

---

docs/.vuepress/components/Terminal.vue

docs: fix terminal rendering

---

packages/koishi/src/quester.ts

Patch:  add missing `ctx.http.delete`

---

README.md

Cherry-pick commit a1939eff8b25ff927675fe80e264c34a55c1dba1 (#387)
Add qa-bot

Add qa-bot

---

packages/core/src/app.ts

Fixes https://github.com/koishijs/koishi/issues/423

fix(core): resolving non-immediate plugin

---

packages/core/src/help.ts

fix(core): fix the command type of help

---

plugins/assets/local/src/index.ts

https://github.com/koishijs/koishi/issues/440

fix(assets-local): Path traversal issue

---

README.md

[canvas](https://github.com/idlist/koishi-plugin-canvas) 过于粗糙，先不写进去了 😂

Add community plugin to README

---

docs/.vuepress/layouts/Home.vue

解决手机查看官网目录被截断问题

---

docs/.vuepress/layouts/Home.vue

docs: add action buttons on index

---

docs/.vuepress/components/PanelView.vue
docs/.vuepress/markdown/highlight.js
docs/.vuepress/markdown/twoslash.js
docs/.vuepress/styles/twoslash.scss
docs/guide/introduction/direct.md

docs: twoslash bugfix

---

docs/.vuepress/components/PanelView.vue
docs/.vuepress/styles/twoslash.scss

`defaultCompilerOptions` 我不管怎么试都无法除去 `undefined`，不知道原因。梦梦之后可以看一下。

docs: twoslash bugfix 3

---

plugins/puppeteer/package.json
plugins/teach/package.json

- fix `puppeteer` & `teach` pkg homepage url

fix: puppeteer & teach pkg homepage url

---

plugins/puppeteer/src/index.ts

fix(plugins/puppeteer): default viewport

---

packages/koishi/src/quester.ts
plugins/adapter/discord/src/ws.ts
plugins/adapter/onebot/package.json
plugins/adapter/onebot/src/ws.ts

Feat: add proxy support for OneBot WS

---

packages/cli/src/locales/ja.yml
packages/cli/src/worker/daemon.ts
packages/core/src/i18n.ts
packages/core/src/locales/en.yml
packages/core/src/locales/fr.yml
packages/core/src/locales/ja.yml
packages/core/src/locales/zh.yml

Alright, ready for the review !!

i18n: experimental japanese localisation

---

packages/helpers/src/index.ts
packages/helpers/src/locales/fr.yml
packages/helpers/src/locales/ja.yml

English location: https://github.com/koishijs/koishi/blob/master/packages/helpers/src/locales/en.yml
------
Question: what is `not-in-group` and in what situation would be used?

i18n: packages/helper experimental ja/fr i18n

---

plugins/adapter/discord/src/utils.ts

fix(discord): matches user mentions like <@id>

---

.github/workflows/publish.yml

没办法在 actions 里测试，不过看上去我本地用 docker 是能构建的

fix(ci): fix docker ci caused by the difference between podman and docker

---

packages/scripts/src/setup.ts

~~didn't test~~
tested ok
fix #709

fix(script): mkdir with short name, fix #709

---

plugins/frontend/manager/client/settings/global.vue

fix(manager): Fix global config unable to save. fix #734

---

packages/core/src/command/validate.ts

fix(core): Null check for verifying the authority of a user, fix #750

---

plugins/common/help/src/index.ts
plugins/common/help/src/locales/en-US.yml
plugins/common/help/src/locales/fr-FR.yml
plugins/common/help/src/locales/ja-JP.yml
plugins/common/help/src/locales/zh-CN.yml
plugins/common/help/src/locales/zh-TW.yml

feat(help): add commands prefixes hints

---

packages/core/src/locales/ru-RU.yml

Updated translation into Russian

i18n: update ru-RU.yml

---

.github/FUNDING.yml

chore(funding): update custom url
