packages/koishi/src/init.ts

```js
module.exports = {
type: "cqhttp:http",
port: 8080,
server: "http://localhost:5700",
plugins: [
"common",
"schedule"
]
}
```
```js
module.exports = {
type: "cqhttp:ws",
server: "ws://localhost:6700",
plugins: [
"common",
"schedule"
]
}
```

Fix `type` in config generated by `koishi init`

---

.mocharc.js
package.json
tsconfig.test.json

According to `tsconfig-paths` documentation,
> Typescript by default mimics the Node.js runtime resolution strategy of modules. But it also allows the use of path mapping which allows arbitrary module paths (that doesn't start with "/" or ".") to be specified and mapped to physical paths in the filesystem. The typescript compiler can resolve these paths from tsconfig so it will compile OK. But if you then try to execute the compiled files with node (or ts-node), it will only look in the node_modules folders all the way up to the root of the filesystem and thus will not find the modules specified by paths in tsconfig.
Adding `tsconfig-paths` solves the unused path-mapping problem.
Btw, `baseUrl` is required when using `paths`.

test: fix path mapping

---

packages/plugin-tools/src/baidu.ts
packages/plugin-tools/src/index.ts

Add plugin-baidu

---

packages/adapter-kaiheila/src/bot.ts
packages/adapter-kaiheila/src/ws.ts

Websocket connection should be less likely to drop now.
- Swaped out `setTimeout` with `setInterval` and clear the interval with lazyness.
- Heartbeat timeout intervals are now 6s, 2s & 4s instead of ms.
- Added default endpoint config.

Kaiheila Adapter: stable ping interval for websocket mode.

---

README.md

.md后缀会404，文档里的网址是.html后缀，不过不带后缀也可以跳转

chore: fix broken links on readme

---

packages/adapter-discord/src/bot.ts

chore(discord): assign App.options.axiosConfig to bot.sendEmbedMessage

---

packages/plugin-common/src/handler.ts

文档中说请求处理函数返回undefined可以忽略请求，但实际开发时这样通不过类型检查。
修改了RequestHandler的定义，允许返回void类型。
----
（抱歉刚才没写完说明误开了pr

plugin-common的请求处理系统，返回undefined无法通过类型检查

---

packages/adapter-discord/src/bot.ts
packages/adapter-discord/src/index.ts

feat(discord): Optimize segment.image sending

---

packages/koishi/src/worker.ts

<https://github.com/koishijs/koishi/blob/d11151502102eba899cca878c4ed5fa7f1d1dcfb/packages/koishi/src/worker.ts#L35>
使用 yml 配置文件的时候如果直接使用 `koishi start` 而没有指定配置文件的话这里的 `configExt` 会是 undefined ，修改之后如果存在文件 `configExt` 就不会是 undefined 从而达到加载 yml 文件的目的了

fix(cli): make 'koishi start' works with koishi.config.yml

---

build/dtsc.ts
docs/guide/unit-tests.md
packages/koishi-core/src/database.ts
packages/koishi-core/src/index.ts
packages/koishi-test-utils/src/memory.ts
packages/koishi-test-utils/tests/memory.spec.ts
packages/plugin-mongo/src/index.ts
packages/plugin-mysql/src/database.ts
packages/plugin-mysql/src/index.ts
packages/plugin-mysql/tests/database.spec.ts

支持 expression
暂时只是在 test utils 中的 mock database 实现了该功能
如果这个语法可以，我会接着这个 pr 将 mysql 与 mongo 实现一遍

feat: support query expression and regex

---

packages/plugin-mongo/src/database.ts
packages/plugin-mongo/src/index.ts

5e23361ea0336cf9f205627510c9886d72a88a32 [FIX] mongo: Unset the default port `27017` in order to avoid MongoParseError while using `mongodb+srv` protocol:
```
MongoParseError: Ports not accepted with 'mongodb+srv' URIs
```
The default value set in initialization is enough: https://github.com/koishijs/koishi/blob/8368dc7698430849dd06cf79e647164d8acf38ff/packages/koishi/src/init.ts#L152

fix(mongo): Unset the default port 27017 to avoid MongoParseError

---

docs/.vuepress/components/ChatMessage.vue
docs/.vuepress/components/PanelView.vue

之所以不为了 `ChatMessage` 给 `PanelView` 加 `chat` class 的原因有三：一方面是因为本来 `PanelView` 的默认情况也就基本都是 `ChatMessage` 在用，所以没有什么隐患；另一方面是因为目前的 `PanelView` 也没支持深色，所以顺便一并加了 variable 获取背景色；再一个如果要给所有的 Chat 都加新 class 的话改动太大了。
`transition` 的值全部是官方给定的值。

docs: add dark/light theme for PanelView/ChatMessage

---

packages/plugin-puppeteer/src/worker.ts

fix(puppeteer): fix the failure to render the fragment from plugin-eval

---

docs/guide/command.md

docs(command): typo

---

packages/koishi-test-utils/src/memory.ts
packages/koishi-test-utils/tests/memory.spec.ts

fix(test-utils): orm expr query behavior for `$eq`, `$ne` and so on

---

plugins/adapter/onebot/src/bot.ts

构造合并转发的时候有用, 因为此时合并转发内容不会经过该函数, 需要用户自行处理

Export `renderText` function to support extrenal use

---

packages/koishi/src/router.ts

Mainly used for mock.
Before:
```ts
const app = new App();
console.log(app._httpServer); // undefined
```
After:
```ts
const app = new App();
console.log(app._httpServer); // an http server
```

koishi: start http server but dont listen if no port

---

plugins/database/mysql/src/index.ts

The following changes are made for the following reason:
1. `char` would use the maximum length to store every string, no matter how long the data stored is. In practice, as for the situations where strings hardly touches the limit, it's better to use `varchar` instead of `char`.
2. `timestamp` is not recommended to use in MySQL, as it may meet the year 2038 problem.

Change some types in MySQL

---

plugins/cache/redis/src/index.ts

`expire` stands for seconds, which is incorrect. It should be changed to `pExpire` for ms.

fix(redis): expire => pexpire

---

packages/koishi/src/quester.ts

Because the `config` in the function is an optional argument, it can be undefined.
And then the code below read its property without an optional notation, so cause the error like:
` TypeError: Cannot read properties of undefined (reading 'headers')`
This PR fixes the error.

fix: undefined reading error in request function

---

plugins/assets/local/src/index.ts
plugins/assets/remote/src/index.ts
plugins/assets/s3/src/index.ts

When the asset file originates from the assets storage provider itself, skips the entire upload process and return the url directly.

feat(assets): skip upload when from same origin

---

plugins/database/mysql/src/index.ts
plugins/database/tests/src/query.ts
plugins/database/tests/src/update.ts

Note that the new test cases added introduce a failure for other database plugins like MongoDB and LevelDB (time comparisons)

fix(mysql): time field should give Date

---

plugins/database/memory/src/storage/node.ts

fixed to make Storage.start() work (probably)
----
fixes #519
>looks like someone didn't realize that `path.extname()` includes the preceeding dot

fix(database-memory): data not loading (#519)

---

plugins/adapter/kaiheila/src/http.ts
plugins/adapter/onebot/src/http.ts
plugins/adapter/onebot/src/ws.ts

There are situations where http server would response without actually make the inbuilt http server listen. In those cases this option assertion could only be annoying.
The situations could be as follows:
- `koishi-nestjs` sharing the same http server with Nest instance, using Nest middleware to redirect requests.
- `koishi-web-connect` exporting router services as Express middlewares.
- `@koishijs/plugin-mock` mocking http requests.

chore: remove option port assertions

---

plugins/database/mongo/src/index.ts

https://www.mongodb.com/docs/manual/reference/command/dbStats/#mongodb-data-dbStats.totalSize
While MongoDB's document above says that the `stats.totalSize` is the sum of
`stats.dataSize` and `stats.storageSize`, it's actually `undefined` in some cases.
So we have to calculate it manually.

fix(mongo): db.totalSize can be undefined, fix #568

---

plugins/adapter/telegram/src/http.ts

This is incorrect in this protocol and should be removed.

patch(telegram): Don't camelCase in webhook protocol

---

packages/koishi/src/quester.ts

解决空代理导致的 websocket 错误
Koishi 4.6.1
go-cqhttp 1.0.0-rc1
当`proxyAgent`为空时使用正向ws连接将报错：
```
[WARNING]: 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
```

fix(core): ws error caused by empty proxyAgent

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/stale.yml

As the title says, these workflows / steps should not run on a fork.
So add an if-check there.

ci: restrict some workflows runs in main repo only

---

packages/utils/src/misc.ts

处理的错误若 error.stack = undefined（如 axios 库的 401 response）会在这行挂掉。

fix(utils): resolve error failed when stack is undefined

---

packages/core/src/command/command.ts

support abbreviated subcommand alias.
e.g.:
```ts
ctx.command('foo').alias('f')
ctx.command('foo.bar').alias('.b')
```
able to trigger by `foo.bar` `foo.b` `f.bar` and `f.b` .

feat(core): support abbreviated subcommand alias

---

plugins/hmr/package.json
plugins/hmr/src/error.ts
plugins/hmr/src/index.ts

I think `console.log` is better then `logger.warn` at from L297 to L309. But in order to follow the logger standard, `logger.warn` is used.

feat(hmr): add syntax output for build errors

---

plugins/common/inspect/src/index.ts

session.quote 不存在 userId 和 channelId 两个属性
附样例
```yml
{ messageId: '-47795126', id: '-47795126', elements: [ Element { type: 'text', attrs: { content: '.inspect' }, children: [] } ], content: '.inspect', user: { id: '3767615641', name: 'narcissus', userId: '3767615641', avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=3767615641&spec=640', username: 'narcissus' }, member: { user: { id: '3767615641', name: 'narcissus', userId: '3767615641', avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=3767615641&spec=640', username: 'narcissus' }, nick: undefined, roles: [ undefined ] }, timestamp: 1709286217000, guild: { id: '292088282' }, channel: { id: '292088282', type: 0 } }
```

fix(inspect): undefined property
